from .bicgstab import BiCGStab as BiCGStab
from .cg import CG as CG
from .cholesky import Cholesky as Cholesky
from .diagonal import Diagonal as Diagonal
from .gmres import GMRES as GMRES
from .lu import LU as LU
from .qr import QR as QR
from .svd import SVD as SVD
from .triangular import Triangular as Triangular
from .tridiagonal import Tridiagonal as Tridiagonal
